-- Clínica Témpora · almacenamiento de formularios y respaldo para Pipedrive.
-- Ejecutar una vez en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  submission_id text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,

  form_version text not null default '',
  source_form text not null default 'Providencia',
  nombre text not null,
  apellido text not null,
  email text not null,
  telefono text not null,
  urgencia_cirugia text not null,
  medio_evaluacion text not null,
  genero text not null,
  horario_contacto text not null,

  delivery_status text not null default 'received'
    check (delivery_status in ('received', 'processing', 'synced', 'failed')),
  make_status text not null default 'pending'
    check (make_status in ('pending', 'success', 'failed', 'not_configured')),
  pipedrive_status text not null default 'pending'
    check (pipedrive_status in ('pending', 'processing', 'success', 'failed', 'not_configured')),
  pipedrive_person_id text,
  pipedrive_deal_id text,
  integration_error text,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_attempt_at timestamptz,
  requeue_requested_at timestamptz,

  utm_id text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  utm_source_platform text,
  utm_creative_format text,
  utm_marketing_tactic text,
  campaign_id text,
  adgroup_id text,
  ad_id text,
  keyword text,
  match_type text,
  network text,
  device text,
  placement text,
  gclid text,
  gbraid text,
  wbraid text,
  fbclid text,
  msclkid text,
  ttclid text,

  page_url text,
  page_path text,
  referrer text,
  raw_payload jsonb not null default '{}'::jsonb,

  constraint leads_email_format check (position('@' in email) > 1),
  constraint leads_phone_format check (telefono ~ '^[0-9]{9}$')
);

create table if not exists public.lead_delivery_events (
  id bigint generated by default as identity primary key,
  submission_id text not null references public.leads(submission_id) on delete cascade,
  event_type text not null
    check (event_type in ('received', 'make_success', 'make_failed', 'queued_offline')),
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_pipedrive_status_idx on public.leads (pipedrive_status, created_at desc);
create index if not exists leads_email_idx on public.leads (lower(email));
create index if not exists leads_phone_idx on public.leads (telefono);
create index if not exists lead_delivery_events_submission_idx
  on public.lead_delivery_events (submission_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at
before update on public.leads
for each row execute function public.set_updated_at();

alter table public.leads enable row level security;
alter table public.lead_delivery_events enable row level security;

drop policy if exists "public can submit leads" on public.leads;
create policy "public can submit leads"
on public.leads
for insert
to anon
with check (
  submission_id <> ''
  and nombre <> ''
  and apellido <> ''
  and position('@' in email) > 1
  and telefono ~ '^[0-9]{9}$'
  and delivery_status = 'received'
  and make_status in ('pending', 'not_configured')
  and pipedrive_status in ('pending', 'not_configured')
  and attempt_count = 0
  and pipedrive_person_id is null
  and pipedrive_deal_id is null
  and integration_error is null
);

drop policy if exists "authenticated users can read leads" on public.leads;
create policy "authenticated users can read leads"
on public.leads
for select
to authenticated
using (true);

drop policy if exists "authenticated users can update leads" on public.leads;
create policy "authenticated users can update leads"
on public.leads
for update
to authenticated
using (true)
with check (true);

drop policy if exists "public can append delivery events" on public.lead_delivery_events;
create policy "public can append delivery events"
on public.lead_delivery_events
for insert
to anon
with check (true);

drop policy if exists "authenticated users can read delivery events" on public.lead_delivery_events;
create policy "authenticated users can read delivery events"
on public.lead_delivery_events
for select
to authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant insert on public.leads to anon;
grant insert on public.lead_delivery_events to anon;
grant select, update on public.leads to authenticated;
grant select on public.lead_delivery_events to authenticated;
grant usage, select on sequence public.lead_delivery_events_id_seq to anon, authenticated;

-- Seguridad operativa:
-- 1. Desactivar "Allow new users to sign up" en Authentication > Providers > Email.
-- 2. Crear únicamente los usuarios internos que podrán entrar a /cms.
-- 3. Make actualiza delivery_status/pipedrive_status usando su conexión segura.
